---
title: "p1_Instacart_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r read_library}
library(readr)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r clean_data}
instacart = read_csv("./instacart_train_data.csv.zip",col_types = "iiiiiciiiiciicc") 
```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A

```{r box_chart}
#the distribution of the order hour of the day for each department
instacart %>%
   mutate(department = fct_reorder(department, order_hour_of_day)) %>%
   plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department,
          colors = "Set2",
          type = "box")
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B

```{r bar_chart}
#how many items are ordered in each department
instacart %>%
  group_by(department) %>%
  summarize(items_ordered = n()) %>%
  mutate(department = fct_reorder(department, items_ordered)) %>% 
  plot_ly(x = ~department, y = ~items_ordered, color = ~department, 
          type = "bar")
```


### Chart C

```{r line plot}
#how many items are ordered in different departments in each hour of the day
instacart %>%
  group_by(department,order_hour_of_day) %>%
  summarize(items_ordered = n())  %>% 
  mutate(text_label = str_c("Department: ", department)) %>%
  plot_ly(x = ~order_hour_of_day, y = ~items_ordered, color = ~department, type = "scatter", mode = "lines", text = ~text_label) 
```